apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-runner-scale-set
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    chart: gha-runner-scale-set
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.9.1
    helm:
      parameters:
        - name: "githubConfigUrl"
          value: "https://github.com/asprin107/spring-petclinic"
        - name: "githubConfigSecret.github_token"
          value: "REPLACE_YOUR_TOKEN_HERE"
        - name: "minRunners"
          value: "1"
        - name: "maxRunners"
          value: "5"
        - name: "containerMode.type"
          value: "dind"
        - name: "controllerServiceAccount.name"
          value: "gha-runner-scale-set-controller-gha-rs-controller"
        - name: "controllerServiceAccount.namespace"
          value: "default"
        - name: "runnerScaleSetName"
          value: "bmt-eks"