apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: {{ .Values.spec.destination.server }}
  project: default

  source:
{{/*    path: charts/grafana*/}}
{{/*    repoURL: https://github.com/grafana/helm-charts.git*/}}
    path: helm/charts/grafana
    repoURL: https://github.com/asprin107/test-engineering.git
    targetRevision: HEAD
    helm:
      parameters:
        - name: service.type
          value: NodePort
        - name: service.nodePort
          value: "30081"
